# -*- coding: utf-8 -*-
"""classification model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZuOKykF0vN8bbtWdX2D0881p90m3eyiA
"""

from sklearn.datasets import load_iris
import pandas as pd

# Load the dataset
iris = load_iris()

# Create a DataFrame for features
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# Add target column (0: setosa, 1: versicolor, 2: virginica)
df['target'] = iris.target

print(df.head())
print("\nDataset Info:")
print(df.info())

from sklearn.model_selection import train_test_split

# Separate features (X) and target (y)
X = df.drop(columns=['target'])
y = df['target']

# Split: 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Training set size: {X_train.shape[0]} rows")
print(f"Testing set size: {X_test.shape[0]} rows")

from sklearn.linear_model import LogisticRegression

# Initialize the model
model = LogisticRegression(max_iter=200)

# Train (fit) the model on the training set
model.fit(X_train, y_train)

print("Model training complete.")

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Make predictions on unseen test data
y_pred = model.predict(X_test)

# Calculate performance metrics
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%\n")

print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))